CREATE TABLE IF NOT EXISTS markers (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    latitude DECIMAL(10, 8) NOT NULL,
    longitude DECIMAL(11, 8) NOT NULL,
    description TEXT,
    added TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    edited TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
); 